### PR TITLE
Feature/grid

### PR DESCRIPTION
**Pull request by douggrubba**
So I guess this is my take on it.

I lifted that grid values from bootstrap and attached their fluid grid to the container.  We should care what the resolution is of the user's device then.

I moved the widget's view from "class" to "rel" and cleared out "class" to make room for 2 vars in the widgets.php config file.  Height and Width can now be set in that file so that you can easily set the sizes w/o having to mess with a widgets view or css files.

Check it out and let me know what you think.

### CODE REVIEW

**Comment by douggrubba** [comment]
haha, also ignore those first 3 commits  :P

**Comment by ghost** [comment]
Cool - I haven't tested this yet but it looks good to me.

**Comment by ghost** [comment]
@ericbarnes what do you think - should this be pulled in?

**Comment by ericlbarnes** [comment]
What do you guys think about just going with bootstrap all together?

**Comment by douggrubba** [comment]
Come to the dark side @ericbarnes 

Haha.  <span class="alert alert-success">Yeah</span>, you know I am down with doing that.

**Comment by ghost** [comment]
That's good with me too

**Comment by ericlbarnes** [comment]
okay bootstrap it is.  I am going to close this :beer:

**Comment by ghost** [comment]
Mmmmm beer

**Pull request closed without merging**
